### ISSUE TITLE
SMTP syntax errors

### ISSUE THREAD

**Issue by DerDakon** [kenchowcn/smtp#2]
It's "MAIL FROM:<" and "RCPT TO:<", i.e. no spaces between colon and opening brace, see [RfC 5321](https://tools.ietf.org/html/rfc5321#page-20).

**Comment by kenchowcn** [comment]
Yes, indeed, thank you very much.

**Comment by DerDakon** [comment]
Has been fixed in fc5808f227b2b4bc74100f12a355430c6da840d4.
